# Swedish translations for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-02-19 22:26+0200\n"
"PO-Revision-Date: 2024-02-19 22:17+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: sv\n"
"Language-Team: sv <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.13.0\n"

#: api/admin/announcement_list_validator.py:35
#, python-format
msgid "Invalid announcement list format: %(announcements)r"
msgstr ""

#: api/admin/announcement_list_validator.py:50
#, python-format
msgid "Too many announcements: maximum is %(maximum)d"
msgstr ""

#: api/admin/announcement_list_validator.py:62
#, python-format
msgid "Duplicate announcement ID: %s"
msgstr ""

#: api/admin/announcement_list_validator.py:71
#, python-format
msgid "Invalid announcement format: %(announcement)r"
msgstr ""

#: api/admin/announcement_list_validator.py:85
#, python-format
msgid "Invalid announcement ID: %(id)s"
msgstr ""

#: api/admin/announcement_list_validator.py:95
#, python-format
msgid "Missing required field: %(field)s"
msgstr ""

#: api/admin/announcement_list_validator.py:141
#, python-format
msgid "Value too short (%(length)d versus %(limit)d characters): %(value)s"
msgstr ""

#: api/admin/announcement_list_validator.py:153
#, python-format
msgid "Value too long (%(length)d versus %(limit)d characters): %(value)s"
msgstr ""

#: api/admin/announcement_list_validator.py:188
#, python-format
msgid "Value for %(field)s is not a date: %(date)s"
msgstr ""

#: api/admin/announcement_list_validator.py:201
#, python-format
msgid "Value for %(field)s must be no earlier than %(minimum)s"
msgstr ""

#: api/admin/problem_details.py:9
msgid "Admin auth not configured"
msgstr ""

#: api/admin/problem_details.py:10
msgid "This circulation manager has not been configured to authenticate admins."
msgstr ""

#: api/admin/problem_details.py:16
msgid "Admin auth mechanism not configured"
msgstr ""

#: api/admin/problem_details.py:17
msgid ""
"This circulation manager has not been configured to authenticate admins "
"with the mechanism you used"
msgstr ""

#: api/admin/problem_details.py:25
msgid "Invalid admin credentials"
msgstr ""

#: api/admin/problem_details.py:26
msgid "Valid library staff credentials are required."
msgstr ""

#: api/admin/problem_details.py:32
msgid "Admin not authorized"
msgstr ""

#: api/admin/problem_details.py:33
msgid "Your admin account is not authorized to make this request."
msgstr ""

#: api/admin/problem_details.py:39
msgid "Invalid CSRF token"
msgstr ""

#: api/admin/problem_details.py:40
msgid "There was an error saving your changes."
msgstr ""

#: api/admin/problem_details.py:46
msgid "Invalid edit"
msgstr ""

#: api/admin/problem_details.py:47
msgid "There was a problem with the edited metadata."
msgstr ""

#: api/admin/problem_details.py:53
msgid "Metadata refresh pending."
msgstr ""

#: api/admin/problem_details.py:54
msgid "The Metadata Wrangler is looking for new data. Check back later."
msgstr ""

#: api/admin/problem_details.py:60 api/admin/problem_details.py:61
msgid "Metadata could not be refreshed."
msgstr ""

#: api/admin/problem_details.py:67
msgid "Genre not found."
msgstr ""

#: api/admin/problem_details.py:68
msgid "One of the submitted genres does not exist."
msgstr ""

#: api/admin/problem_details.py:74
msgid "Incompatible genre."
msgstr ""

#: api/admin/problem_details.py:75
msgid "The genre is incompatible with the fiction status of the work."
msgstr ""

#: api/admin/problem_details.py:81
msgid "Erotica is for Adults Only."
msgstr ""

#: api/admin/problem_details.py:82
msgid "The Erotica genre is incompatible with the submitted Audience."
msgstr ""

#: api/admin/problem_details.py:88
msgid "Invalid series position."
msgstr ""

#: api/admin/problem_details.py:89
msgid "The series position must be a number or blank."
msgstr ""

#: api/admin/problem_details.py:95
msgid "Invalid date format."
msgstr ""

#: api/admin/problem_details.py:96
msgid "A date must be in the format YYYY-MM-DD."
msgstr ""

#: api/admin/problem_details.py:102
msgid "Unknown language."
msgstr ""

#: api/admin/problem_details.py:103
msgid "The submitted language is not one of the known languages."
msgstr ""

#: api/admin/problem_details.py:109
msgid "Unknown location."
msgstr ""

#: api/admin/problem_details.py:110
msgid "The submitted geographic location cannot be found."
msgstr ""

#: api/admin/problem_details.py:116
msgid "Unknown role."
msgstr ""

#: api/admin/problem_details.py:117
msgid "One of the submitted roles is not one of the known roles."
msgstr ""

#: api/admin/problem_details.py:123
msgid "Unknown medium."
msgstr ""

#: api/admin/problem_details.py:124
msgid "The submitted medium is not one of the known media types."
msgstr ""

#: api/admin/problem_details.py:130
msgid "Invalid rating."
msgstr ""

#: api/admin/problem_details.py:131
msgid "The rating must be a number in the rating scale."
msgstr ""

#: api/admin/problem_details.py:137
msgid "Invalid image"
msgstr ""

#: api/admin/problem_details.py:138
msgid "The submitted image is invalid."
msgstr ""

#: api/admin/problem_details.py:144
msgid "Library short name already in use"
msgstr ""

#: api/admin/problem_details.py:145
msgid ""
"The library short name must be unique, and there's already a library with"
" the specified short name."
msgstr ""

#: api/admin/problem_details.py:153
msgid "Missing collection."
msgstr ""

#: api/admin/problem_details.py:154
msgid "The specified collection does not exist."
msgstr ""

#: api/admin/problem_details.py:160
msgid "Missing analytics name."
msgstr ""

#: api/admin/problem_details.py:161
msgid "You must identify the analytics service by its name."
msgstr ""

#: api/admin/problem_details.py:167
msgid "Cannot delete collection with children"
msgstr ""

#: api/admin/problem_details.py:168
msgid ""
"The collection is the parent of at least one other collection, so it "
"can't be deleted."
msgstr ""

#: api/admin/problem_details.py:176
msgid "No protocol for new service"
msgstr ""

#: api/admin/problem_details.py:177
msgid ""
"The specified service doesn't exist. You can create it, but you must "
"specify a protocol."
msgstr ""

#: api/admin/problem_details.py:185
msgid "Unknown protocol"
msgstr ""

#: api/admin/problem_details.py:186
msgid "The protocol is not one of the known protocols."
msgstr ""

#: api/admin/problem_details.py:192
msgid "Cannot change protocol"
msgstr ""

#: api/admin/problem_details.py:193
msgid "A protocol can't be changed once it has been set."
msgstr ""

#: api/admin/problem_details.py:199
msgid "Missing service name."
msgstr ""

#: api/admin/problem_details.py:200
msgid "You must identify the service by its name."
msgstr ""

#: api/admin/problem_details.py:206
msgid "Protocol does not support parents"
msgstr ""

#: api/admin/problem_details.py:207
msgid "You attempted to add a parent but the protocol does not support parents."
msgstr ""

#: api/admin/problem_details.py:215
msgid "Protocol does not support settings"
msgstr ""

#: api/admin/problem_details.py:216
msgid ""
"You attempted to update settings for a protocol that does not support "
"settings."
msgstr ""

#: api/admin/problem_details.py:224
msgid "Missing parent"
msgstr ""

#: api/admin/problem_details.py:225
msgid "You attempted to add a parent that does not exist."
msgstr ""

#: api/admin/problem_details.py:231
msgid "No such library"
msgstr ""

#: api/admin/problem_details.py:232
msgid "A library in your request does not exist."
msgstr ""

#: api/admin/problem_details.py:238
msgid "Incomplete configuration"
msgstr ""

#: api/admin/problem_details.py:239
msgid "The configuration is missing a required field."
msgstr ""

#: api/admin/problem_details.py:245
msgid "Duplicate integration"
msgstr ""

#: api/admin/problem_details.py:246
msgid "A given site can only support one integration of this type."
msgstr ""

#: api/admin/problem_details.py:252
msgid "Integration name already in use"
msgstr ""

#: api/admin/problem_details.py:253
msgid ""
"The integration name must be unique, and there's already an integration "
"with the specified name."
msgstr ""

#: api/admin/problem_details.py:261
msgid "Integration URL already in use"
msgstr ""

#: api/admin/problem_details.py:262
msgid "There's already an integration of this type for this URL."
msgstr ""

#: api/admin/problem_details.py:268
msgid "Incompatible use of integration"
msgstr ""

#: api/admin/problem_details.py:269
msgid ""
"You tried to use an integration in a way incompatible with the goal of "
"that integration"
msgstr ""

#: api/admin/problem_details.py:277
msgid "Missing integration"
msgstr ""

#: api/admin/problem_details.py:278
msgid "The specified integration does not exist."
msgstr ""

#: api/admin/problem_details.py:284
msgid "Missing pgcrypto database extension"
msgstr ""

#: api/admin/problem_details.py:285
msgid ""
"You tried to store a password for an individual admin, but the database "
"does not have the pgcrypto extension installed."
msgstr ""

#: api/admin/problem_details.py:293
msgid "Missing admin"
msgstr ""

#: api/admin/problem_details.py:294
msgid "The specified admin does not exist."
msgstr ""

#: api/admin/problem_details.py:300
msgid "Missing service"
msgstr ""

#: api/admin/problem_details.py:301
msgid "The specified service does not exist."
msgstr ""

#: api/admin/problem_details.py:307
msgid "Invalid configuration option"
msgstr ""

#: api/admin/problem_details.py:308
msgid "The configuration has an invalid value."
msgstr ""

#: api/admin/problem_details.py:314
msgid "Invalid email format"
msgstr ""

#: api/admin/problem_details.py:315
msgid "You must enter a valid email address."
msgstr ""

#: api/admin/problem_details.py:321
msgid "Invalid URL format"
msgstr ""

#: api/admin/problem_details.py:322
msgid "You must enter a valid URL."
msgstr ""

#: api/admin/problem_details.py:328
msgid "Invalid number format"
msgstr ""

#: api/admin/problem_details.py:329
msgid "You must enter a number."
msgstr ""

#: api/admin/problem_details.py:335
msgid "Invalid external type regular expression"
msgstr ""

#: api/admin/problem_details.py:336
msgid "The specified external type regular expression does not compile."
msgstr ""

#: api/admin/problem_details.py:342
msgid "Invalid library identifier restriction regular expression"
msgstr ""

#: api/admin/problem_details.py:343
msgid ""
"The specified library identifier restriction regular expression does not "
"compile."
msgstr ""

#: api/admin/problem_details.py:351
msgid "Multiple basic authentication services"
msgstr ""

#: api/admin/problem_details.py:352
msgid ""
"Each library can only have one patron authentication service using basic "
"auth."
msgstr ""

#: api/admin/problem_details.py:360
msgid "No such patron"
msgstr ""

#: api/admin/problem_details.py:361
msgid ""
"The specified patron doesn't exist, or is associated with a different "
"library."
msgstr ""

#: api/admin/problem_details.py:369
msgid "Missing sitewide setting key"
msgstr ""

#: api/admin/problem_details.py:370
msgid "A key is required to change a sitewide setting."
msgstr ""

#: api/admin/problem_details.py:376
msgid "Missing sitewide setting value"
msgstr ""

#: api/admin/problem_details.py:377
msgid "A value is required to change a sitewide setting."
msgstr ""

#: api/admin/problem_details.py:383
msgid "Multiple sitewide services"
msgstr ""

#: api/admin/problem_details.py:384
msgid ""
"You tried to create a new sitewide service, but a sitewide service of the"
" same type is already configured."
msgstr ""

#: api/admin/problem_details.py:392
msgid "Multiple services for library"
msgstr ""

#: api/admin/problem_details.py:393
msgid "Each library can only have one service of this type."
msgstr ""

#: api/admin/problem_details.py:399
msgid "Missing custom list"
msgstr ""

#: api/admin/problem_details.py:400
msgid "The specified custom list doesn't exist."
msgstr ""

#: api/admin/problem_details.py:406
msgid "Cannot change library for custom list"
msgstr ""

#: api/admin/problem_details.py:407
msgid "A custom list's associated library cannot be changed once it is set.."
msgstr ""

#: api/admin/problem_details.py:413
msgid "Custom list name already in use"
msgstr ""

#: api/admin/problem_details.py:414
msgid "The library already has a custom list with that name."
msgstr ""

#: api/admin/problem_details.py:420
msgid "An auto update custom list cannot have entries"
msgstr ""

#: api/admin/problem_details.py:421
msgid "Entries are automatically managed for auto update custom lists"
msgstr ""

#: api/admin/problem_details.py:427
msgid "Collection not associated with library"
msgstr ""

#: api/admin/problem_details.py:428
msgid ""
"You can't add a collection to a list unless it is associated with the "
"list's library."
msgstr ""

#: api/admin/problem_details.py:436
msgid "Missing lane"
msgstr ""

#: api/admin/problem_details.py:437
msgid ""
"The specified lane doesn't exist, or is associated with a different "
"library."
msgstr ""

#: api/admin/problem_details.py:445
msgid "Cannot edit default lane"
msgstr ""

#: api/admin/problem_details.py:446
msgid "You can't change one of the default auto-generated lanes."
msgstr ""

#: api/admin/problem_details.py:452
msgid "No display name for lane"
msgstr ""

#: api/admin/problem_details.py:453
msgid "A custom lane must have a name."
msgstr ""

#: api/admin/problem_details.py:459
msgid "No custom lists for lane"
msgstr ""

#: api/admin/problem_details.py:460
msgid "A custom lane must have at least one associated list."
msgstr ""

#: api/admin/problem_details.py:466
msgid "Lane with parent and display name already exists"
msgstr ""

#: api/admin/problem_details.py:467
msgid ""
"You cannot create a lane with the same parent and display name as an "
"existing lane."
msgstr ""

#: api/admin/problem_details.py:475
msgid "Cannot show lane with hidden parent"
msgstr ""

#: api/admin/problem_details.py:476
msgid "You can only make a lane visible if its parent is already visible."
msgstr ""

#: api/admin/problem_details.py:482
msgid "The collection does not support registration"
msgstr ""

#: api/admin/problem_details.py:483
msgid "The collection does not support registration."
msgstr ""

#: api/admin/problem_details.py:489 api/admin/problem_details.py:490
msgid "Failed to run self tests."
msgstr ""

#: api/admin/problem_details.py:496
msgid "Missing identifier"
msgstr ""

#: api/admin/problem_details.py:497
msgid "No identifier was used."
msgstr ""

#: api/admin/problem_details.py:503
msgid "Source collection missing"
msgstr ""

#: api/admin/problem_details.py:504
msgid "A source collection is not present in the library."
msgstr ""

#: api/admin/problem_details.py:510
msgid "Entry not valid for library"
msgstr ""

#: api/admin/problem_details.py:511
msgid ""
"An entry in the customlist was not valid for the library being shared "
"with."
msgstr ""

#: api/admin/problem_details.py:519
msgid "Cannot delete the Custom List share"
msgstr ""

#: api/admin/problem_details.py:520
msgid "Unable to delete the shared status of the given list"
msgstr ""

#: api/admin/validator.py:61
#, python-format
msgid "\"%(email)s\" is not a valid email address."
msgstr ""

#: api/admin/validator.py:86
#, python-format
msgid "\"%(url)s\" is not a valid URL."
msgstr ""

#: api/admin/validator.py:118
#, python-format
msgid "\"%(number)s\" is not a number."
msgstr ""

#: api/admin/validator.py:125
#, python-format
msgid "%(field)s must be greater than %(min)s."
msgstr ""

#: api/admin/validator.py:133
#, python-format
msgid "%(field)s cannot be greater than %(max)s."
msgstr ""

